version: '3.3'
services:
  db-postgree:
    image: postgres:14.1-alpine
    restart: always
    environment:
      # You can use whatever user you like
      POSTGRES_USER: "admin"
      # You can use whatever password you like
      POSTGRES_PASSWORD: "admin"
      # You can use whatever database name you like
      POSTGRES_DB: "labs"
    ports:
      # <Port exposed> : < PostgreSQL Port running inside container>
      - "5432:5432"
    expose:
      # Opens port 3306 on the container
      - "${DB_PORT}"
      # Where our data will be persisted
    volumes:
      - my-db-postgree:/var/lib/postgresql/
# Names our volume
volumes:
  my-db-postgree: